# Generated by Django 2.1.5 on 2020-04-15 14:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20200414_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 4, 15, 19, 34, 36, 738005))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2020, 4, 15, 19, 34, 36, 738005))),
                ('is_active', models.BooleanField(default=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 19, 34, 36, 734014)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='comment_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 19, 34, 36, 743076)),
        ),
    ]
