# Generated by Django 2.1.5 on 2020-04-15 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200415_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 20, 36, 21, 927286)),
        ),
        migrations.AlterField(
            model_name='author',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 20, 36, 21, 927286)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 20, 36, 21, 923459)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='comment_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 20, 36, 21, 931286)),
        ),
    ]
