# Generated by Django 2.1.5 on 2020-04-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200415_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default='Wil update Later', max_length=200),
            preserve_default=False,
        ),
    ]
