# Generated by Django 2.1.5 on 2020-04-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default='Will add later', max_length=2000),
            preserve_default=False,
        ),
    ]
