# Generated by Django 2.1.5 on 2020-04-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='author',
            field=models.IntegerField(max_length=100000),
        ),
    ]
