# Generated by Django 2.1.5 on 2020-04-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200430_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='author',
            field=models.IntegerField(),
        ),
    ]
