# Generated by Django 2.1.5 on 2020-05-02 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200430_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postview',
            old_name='post_id',
            new_name='post',
        ),
        migrations.AddField(
            model_name='postview',
            name='viewed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
