# Generated by Django 2.1.5 on 2020-05-02 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200502_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='unfollowed_at',
        ),
    ]
