# Generated by Django 2.1.5 on 2020-05-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_remove_follow_unfollowed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='post_id',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='postlike',
            name='unliked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
