# Generated by Django 2.1.5 on 2020-05-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200503_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
