# Generated by Django 2.1.5 on 2020-05-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20200516_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='display_image',
            field=models.ImageField(help_text='This image will be displayed as thumbnail for this article. Try to choose a relevant image describing the content of this article.', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_caption',
            field=models.CharField(blank=True, help_text='Caption for image attached', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='Hold control while selecting multiple tags.', null=True, to='blog.Tag'),
        ),
    ]
