# Generated by Django 2.1.5 on 2020-05-26 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_bookmarkpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarkpost',
            old_name='boorkmarked_by',
            new_name='bookmarked_by',
        ),
    ]
